
name: Build HUTB engine

on:
  workflow_dispatch:
    
jobs:
  build_engine:
    runs-on: windows-2025
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Test VS Installation
        run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin"
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\MSBuild.exe --help"

      - name: Set up environment
        run: |
          ./Setup.bat
          ./GenerateProjectFiles.bat

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
       
      - name: Build HUTB engine
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\MSBuild.exe" Engine\Intermediate\ProjectFiles\UE4.vcxproj
        
